CREATE TABLE 'events' (
	'id' MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	'key' varchar(255) NOT NULL,
	'url' varchar(255) DEFAULT NULL,
	'created' DATETIME DEFAULT CURRENT_TIMESTAMP,
	'updated' TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	PRIMARY KEY ('id'),
	UNIQUE KEY 'key' ('key')
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE 'performers' (
	'id' MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
	'name' varchar(255) NOT NULL,
	'imageUrl' varchar(255) DEFAULT NULL,
	'highlight' TINYINT(1) NOT NULL DEFAULT 0,
	'created' DATETIME DEFAULT CURRENT_TIMESTAMP,
	'updated' TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	PRIMARY KEY ('id'),
	UNIQUE KEY 'name' ('name')
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;